---
# Name your file secrets.yml

development:
  DB_FILENAME: db/local/dev.db
  GITHUB_TOKEN: GITHUB_TOKEN

test:
  DB_FILENAME: db/local/test.db
  GITHUB_TOKEN: GITHUB_TOKEN

production:
  GITHUB_TOKEN: GITHUB_TOKEN