---
bearer-token:
  token: eyJhbGciOiJIUzliNiJ9.eyJhdWQiOilwNzEzNDA10DBmNTA3NTU3M2|yZjZiODhjM2EOMW/mZSIsInN1Yi|6|jY1MjkxM2Q1Mzc4MDY MDEZOWEXOGZiNilsI nNjb3BIcy16WyJhcGIfcmVhZCJdLCJ2ZXJzaW9uljoxfQ.Yqm6Vnogx8KWsk0mJinq|moY6KzUHB5JKG7CnyJPK24